development: &default
  adapter: postgresql
  database: nested_dev
  encoding: utf8
  min_messages: warning
  pool: <%= Integer(ENV.fetch("DB_POOL", 5)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: nested_test

production:
  <<: *default
  database: nested_prod
  pool: 15